### ISSUE TITLE
Use IBM calendar api instead

### ISSUE THREAD

**Issue by MetaiR** [abbasiehsan1991/PersianCalendarConvertor#1]
here u can find how to use IBM apis: https://stackoverflow.com/a/23386074/6442877
(remember the imports)
the latest version of this library can be found in here https://mvnrepository.com/artifact/com.ibm.icu/icu4j

**Comment by abbasiehsan1991** [comment]
Thank you, I used this library and it's very strong.
But there is a weak point for of size of this library if you want to use it in Android applications.
it can increase the size of application near 5MB!!!
For an android application is too much.

**Comment by MetaiR** [comment]
@abbasiehsan1991 
maybe this helps
https://stackoverflow.com/a/42216428/6442877
